# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 14 02:00:58 2020
# ------------------------------------------------

package:
    name: pdfminer.six
    version: '20200726'
source:
    sha256: 77f0b6953f36aeeeb45ab959fabd8dfc964b7926676d5df3ac2f949cd4d524a3
    url: https://github.com/pdfminer/pdfminer.six/archive/20200726.tar.gz
build:
    noarch: python
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/pdfminer.six_1597370518565/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps -vv
    string: py_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_14
        - libgomp 9.3.0 h24d8f2e_14
        - libstdcxx-ng 9.3.0 hdf63c60_14
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - pip 20.2.2 py_0
        - python 3.8.5 h4d41432_2_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.5.0 py38h32f6830_0
        - sqlite 3.32.3 h4cf870e_1
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1007
    run:
        - chardet
        - cryptography
        - python >=3.4
        - sortedcontainers
test:
    commands:
        - pdf2txt.py -h
        - dumppdf.py -h
    imports:
        - pdfminer
about:
    description: 'Pdfminer.six is a community maintained fork of the original PDFMiner.

        It is a tool for extracting information from PDF documents.

        It focuses on getting and analyzing text data. Pdfminer.six extracts

        the text from a page directly from the sourcecode of the PDF.

        It can also be used to get the exact location, font or color of the text.

        '
    dev_url: https://github.com/pdfminer/pdfminer.six
    doc_url: https://pdfminersix.readthedocs.io
    home: https://github.com/pdfminer/pdfminer.six
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: PDF parser and analyzer
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - estshorter
        - pmlandwehr
        - pvanheus
