# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Tue Feb 25 11:52:55 2020
# ------------------------------------------------

package:
    name: pythonocc-core
    version: 7.4.0
source:
    sha256: c53481e8b7387b7d3b5f717e86ef8a78849d5041e9cb2966dc6ed4210a3aceac
    url: https://github.com/tpaviot/pythonocc-core/archive/7.4.0.tar.gz
build:
    number: '0'
    string: py38ha02cdc8_0
requirements:
    build:
        - cmake 3.16.4 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - swig 4.0.1 0
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - ca-certificates 2019.11.28 hecc5488_0
        - fontconfig 2.13.1 hb964e45_1001
        - freetype 2.10.0 h563cfd7_1
        - icu 64.2 he025d50_1
        - libiconv 1.15 hfa6e2cd_1005
        - libpng 1.6.37 h7602738_0
        - libxml2 2.9.10 h9ce36c8_0
        - occt 7.4.0 h823b557_1
        - openssl 1.1.1d hfa6e2cd_0
        - python 3.8.1 he1f5543_2
        - sqlite 3.30.1 hfa6e2cd_0
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - occt >=7.4.0,<7.5.0a0
        - python >=3.8,<3.9.0a0
        - six
        - tbb >=2019.9
        - vc >=14,<15.0a0
test:
    imports:
        - OCC
        - OCC.Core.BRepPrimAPI
    requires:
        - pyqt >=5
    source_files:
        - test
about:
    description: 'pythonocc is a python package whose purpose is

        to provide 3D modeling features. It is intended

        to CAD/PDM/PLM and BIM related development.

        '
    dev_url: https://github.com/tpaviot/pythonocc-core
    home: http://www.pythonocc.org/
    license: LGPL-3.0
    license_family: LGPL
    license_file: LICENSE
    summary: python bindings for opencascade (occt)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
