# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Mar 20 14:48:59 2020
# ------------------------------------------------

package:
    name: occt
    version: 7.4.0
source:
    fn: occt-7.4.0.tar.gz
    patches:
        - fix-brepblend.patch
        - fix-private-linking.patch
        - no-xmu.patch
    sha256: 9614c2075cef53e30b25317fc8fcfb71d60a69181d562e1c56469ed8e54ad758
    url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V7_4_0;sf=tgz
build:
    number: '3'
    string: h823b557_3
requirements:
    build:
        - cmake 3.16.4 he025d50_0
        - ninja 1.10.0 h1ad3211_0
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - fontconfig 2.13.1 hb964e45_1001
        - freetype 2.9.1 h563cfd7_1006
        - icu 64.2 he025d50_1
        - libiconv 1.15 hfa6e2cd_1006
        - libpng 1.6.37 hfe6a214_1
        - libxml2 2.9.10 h9ce36c8_0
        - tbb 2019.9 he980bc4_1
        - tbb-devel 2019.9 he980bc4_1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - zlib 1.2.11 h2fa13f4_1006
    run:
        - fontconfig >=2.13.1,<3.0a0
        - fontconfig >=2.13.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - tbb >=2019.9
        - vc >=14,<15.0a0
test:
    commands:
        - cmake -G "Ninja" .
    files:
        - CMakeLists.txt
    requires:
        - cmake
        - ninja
about:
    description: 'Open Cascade Technology (OCCT), formerly called CAS.CADE

        is an open source software development platform for 3D CAD,

        CAM, CAE, etc. that is developed and supported by Open Cascade SAS.

        '
    dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git
    doc_url: https://www.opencascade.com/content/documentation
    home: https://www.opencascade.com/
    license: LGPL-2.1
    license_family: LGPL
    license_file: LICENSE_LGPL_21.txt
    summary: this is the occ (opencascade) CAD-Kernel
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - looooo
