# This file created by conda-build 3.20.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Sep  6 23:40:38 2020
# ------------------------------------------------

package:
    name: trimesh
    version: 3.8.6
source:
    fn: trimesh-3.8.6.tar.gz
    sha256: 51ab68cbf3eddb7e735af79aef9c50ed6385981d0e969b8e8f821fa7a5108103
    url: https://pypi.io/packages/source/t/trimesh/trimesh-3.8.6.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/trimesh_1599435692796/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: pyh9f0ad1d_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - pip 20.2.2 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - numpy
        - python
    run_constrained:
        - chardet
        - colorlog
        - jsonschema
        - lxml
        - meshio
        - msgpack-python
        - networkx
        - pillow
        - psutil
        - pycollada
        - pyglet
        - requests
        - rtree
        - scikit-image
        - scipy
        - setuptools
        - shapely
        - sympy
        - triangle
        - xxhash
test:
    commands:
        - python -c "import trimesh"
about:
    dev_url: https://github.com/mikedh/trimesh
    home: https://github.com/mikedh/trimesh
    license: MIT
    license_file: LICENSE.md
    summary: Import, export, process, analyze and view triangular meshes.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mikedh
        - pauldmccarthy
