# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Sun Aug 23 21:58:23 2020
# ------------------------------------------------

package:
    name: meshpy
    version: 2018.2.1
source:
    fn: MeshPy-2018.2.1.tar.gz
    sha256: 4e6d18c2d19cda540967b6dc6ca844926020c9134cb4075c0f73d47fbbdb2f9e
    url: https://pypi.io/packages/source/M/MeshPy/MeshPy-2018.2.1.tar.gz
build:
    number: '1001'
    script:
        - D:\bld\meshpy_1598220128844\_h_env\python.exe -m pip install . --no-deps
            -v
        - echo src/cpp/tetgen-LICENSE >> doc/faq.rst
    string: py38h251f6bf_1001
requirements:
    build:
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - appdirs 1.4.3 py_1
        - atomicwrites 1.4.0 pyh9f0ad1d_0
        - attrs 20.1.0 pyh9f0ad1d_0
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - colorama 0.4.3 py_0
        - decorator 4.4.2 py_0
        - iniconfig 1.0.1 pyh9f0ad1d_0
        - intel-openmp 2020.1 216
        - libblas 3.8.0 16_mkl
        - libcblas 3.8.0 16_mkl
        - liblapack 3.8.0 16_mkl
        - mkl 2020.1 216
        - more-itertools 8.4.0 py_0
        - numpy 1.16.5 py38hc71023c_0
        - openssl 1.1.1g he774522_1
        - packaging 20.4 pyh9f0ad1d_0
        - pip 20.2.2 py_0
        - pluggy 0.13.1 py38h32f6830_2
        - py 1.9.0 pyh9f0ad1d_0
        - pybind11 2.5.0 py38heaebd3c_0
        - pyparsing 2.4.7 pyh9f0ad1d_0
        - pytest 6.0.1 py38h32f6830_0
        - python 3.8.5 h60c2a47_5_cpython
        - python_abi 3.8 1_cp38
        - pytools 2020.4 pyh9f0ad1d_0
        - setuptools 49.6.0 py38h32f6830_0
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.33.0 he774522_0
        - toml 0.10.1 pyh9f0ad1d_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - wheel 0.35.1 pyh9f0ad1d_0
        - wincertstore 0.2 py38_1003
    run:
        - numpy
        - python >=3.8,<3.9.0a0
        - python_abi 3.8.* *_cp38
        - pytools
        - six
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - pytest test
    imports:
        - meshpy
    requires:
        - pytest
    source_files:
        - test/*
about:
    description: '

        MeshPy offers quality triangular and tetrahedral mesh generation for

        Python. Meshes of this type are chiefly used in finite-element

        simulation codes, but also have many other applications ranging from

        computer graphics to robotics.


        In order to generate 2D and 3D meshes, MeshPy provides Python interfaces

        to three well-regarded mesh generators,

        [Triangle](http://www.cs.cmu.edu/~quake/triangle.html) by J. Shewchuk,

        [TetGen](http://tetgen.berlios.de/) by Hang Si, and

        [gmsh](http://www.geuz.org/gmsh/) by Christophe Geuzaine and

        Jean-Francois Remacle. The former two are included in the package in

        slightly modified versions. A generic mesh reader for the latter is

        included, as is an easy way to run gmsh from a Python script.


        As of Version 0.91.2, MeshPy also works with Python 3.

        '
    dev_url: https://github.com/inducer/meshpy
    doc_url: https://documen.tician.de/meshpy
    home: http://github.com/inducer/meshpy
    license: MIT AND LicenseRef-Proprietary-Triangle AND AGPL-3.0-or-later
    license_file: doc/faq.rst
    summary: Triangular and Tetrahedral Mesh Generator
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - inducer
        - isuruf
