# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Aug 21 06:14:42 2020
# ------------------------------------------------

package:
    name: shapely
    version: 1.7.1
source:
    sha256: 1641724c1055459a7e2b8bbe47ba25bdc89554582e62aec23cb3f3ca25f9b129
    url: https://pypi.io/packages/source/S/Shapely/Shapely-1.7.1.tar.gz
build:
    number: '0'
    string: py38hc96c142_0
requirements:
    build:
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - cython 0.29.21 py38h7ae7562_0
        - geos 3.8.1 he025d50_0
        - intel-openmp 2020.1 216
        - libblas 3.8.0 16_mkl
        - libcblas 3.8.0 16_mkl
        - liblapack 3.8.0 16_mkl
        - mkl 2020.1 216
        - numpy 1.16.5 py38hc71023c_0
        - openssl 1.1.1g he774522_1
        - pip 20.2.2 py_0
        - python 3.8.5 h60c2a47_4_cpython
        - python_abi 3.8 1_cp38
        - setuptools 49.6.0 py38h32f6830_0
        - sqlite 3.33.0 he774522_0
        - vc 14.1 h869be7e_1
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - wheel 0.35.1 pyh9f0ad1d_0
        - wincertstore 0.2 py38_1003
    run:
        - geos >=3.8.1,<3.8.2.0a0
        - numpy >=1.16.5,<2.0a0
        - python >=3.8,<3.9.0a0
        - python_abi 3.8.* *_cp38
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
test:
    commands:
        - pytest tests --with-speedups
    imports:
        - shapely
        - shapely.algorithms
        - shapely.examples
        - shapely.geometry
        - shapely.geos
        - shapely.speedups
        - shapely.speedups._speedups
        - shapely.vectorized
        - shapely.vectorized._vectorized
    requires:
        - pytest
    source_files:
        - tests
about:
    home: https://github.com/Toblerity/Shapely
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Python package for manipulation and analysis of geometric objects in
        the Cartesian plane
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pelson
        - phobson
        - xylar
