# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun 20 14:16:59 2018
# ------------------------------------------------

package:
    name: appdirs
    version: 1.4.3
source:
    sha256: 9e5896d1372858f8dd3344faf4e5014d21849c756c8d5701f78f8a103b372d92
    url: https://pypi.io/packages/source/a/appdirs/appdirs-1.4.3.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 39.2.0 py27_0
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.0 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - python
test:
    imports:
        - appdirs
about:
    home: http://github.com/ActiveState/appdirs
    license: MIT
    license_file: LICENSE.txt
    summary: A small Python module for determining appropriate platform-specific dirs.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
