# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: libopencv
    version: 4.0.1
source:
    -   git_rev: 4.0.1
        git_url: https://github.com/opencv/opencv
        patches:
            - 0001-Use-OpenCV_INSTALL_BINARIES_PREFIX-instead-of-hardco.patch
            - 0003-2-pythons-Debug-cmake-dependency-stuff.patch
            - 0004-2-pythons-Debug-all-variables-in-modules-python-CMak.patch
    -   fn: opencv_contrib-4.0.1.tar.gz
        folder: opencv_contrib-4.0.1
        sha256: 0d8acbad4b7074cfaafd906a7419c23629179d5e98894714402090b192ef8237
        url: https://github.com/opencv/opencv_contrib/archive/4.0.1.tar.gz
build:
    ignore_run_exports:
        - libprotobuf
    number: 0
    run_exports:
        - libopencv >=4.0.1,<4.0.2.0a0
    string: hbb9e17c_0
requirements:
    build:
        - cmake 3.14.0 h33f27b4_0
        - jom 1.1.2 h3bd88b9_0
        - m2-filesystem 2016.04 4
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-pkg-config 0.29.1 2
        - msys2-conda-epoch 20160418 1
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - vs2017_win-64 19.16.27032.1 hb4161e2_0
        - vswhere 2.7.1 h21ff451_0
    host:
        - eigen 3.3.7 h74a9793_0
        - jpeg 9b hb83a4c4_2
        - libpng 1.6.37 h2a8f88b_0
        - libtiff 4.0.10 hb898794_2
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - xz 5.2.4 h2fa13f4_4
        - zlib 1.2.11 h62dcd97_3
        - zstd 1.3.7 h508b16e_0
    run:
        - jpeg >=9b,<10a
        - libpng >=1.6.37,<1.7.0a0
        - libtiff >=4.0.10,<5.0a0
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012,<15.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - pushd test-cmake
        - cmake . -DOpenCV_STATIC=OFF -DOpenCV_SHARED=ON -G"Visual Studio 14 2015
            Win64"
        - cmake --build . --config Release
        - popd
        - if not exist %PREFIX%\\Library\\bin\\opencv_aruco342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_bgsegm342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_calib3d342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ccalib342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_core342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_datasets342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_dnn342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_dpm342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_face342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_features2d342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_flann342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_fuzzy342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_highgui342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_imgcodecs342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_imgproc342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_line_descriptor342.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ml342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_objdetect342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_optflow342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_phase_unwrapping342.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_photo342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_plot342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_reg342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_rgbd342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_saliency342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_shape342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_stereo342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_stitching342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_structured_light342.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_superres342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_surface_matching342.dll exit
            1
        - if not exist %PREFIX%\\Library\\bin\\opencv_text342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_tracking342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_video342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_videoio342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_videostab342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xfeatures2d342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_ximgproc342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xobjdetect342.dll exit 1
        - if not exist %PREFIX%\\Library\\bin\\opencv_xphoto342.dll exit 1
    files:
        - test-cmake/CMakeLists.txt
        - test-cmake/DisplayImage.cpp
        - test.cpp
    requires:
        - cmake
        - vs2017_win-64
about:
    description: 'OpenCV (Open Source Computer Vision Library) includes several hundreds
        of computer vision algorithms.

        It has a modular structure,which means that the package includes several shared
        or static libraries.

        '
    doc_source_url: https://github.com/opencv/opencv/tree/master/doc
    doc_url: http://docs.opencv.org/
    home: http://opencv.org/
    license: BSD 3-clause
    license_family: BSD
    summary: Computer vision and machine learning software library.
extra:
    copy_test_source_files: true
    final: true
