# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\projects\fontconfig-feedstock\recipe, last modified Thu Mar 14 13:14:34 2019
# ------------------------------------------------

package:
    name: fontconfig
    version: 2.13.1
source:
    patches:
        - 0001-Disable-test-bz106632.patch
        - 0002-Disable-some-more-Windows-unfriendly-tests.patch
        - 0003-Import-MSVC-compatibility-files-from-ShiftMediaProje.patch
        - 0004-SMB-getopt.h-also-add-this.patch
        - 0005-Make-private-pkg-config-requirements-public.patch
    sha256: f655dd2a986d7aa97e052261b36aa67b0a64989496361eca8d604e6414006741
    url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.1.tar.bz2
build:
    number: '1000'
    run_exports:
        - fontconfig >=2.13.1,<3.0a0
    string: h2c6e35d_1000
requirements:
    build:
        - gettext 0.19.8.1 hb01d8f6_1001
        - libffi 3.2.1 h6538335_1005
        - libiconv 1.15 hfa6e2cd_1004
        - m2-autoconf 2.69 4
        - m2-automake1.15 1.15 3
        - m2-base 1.0.0 2
        - m2-bash 4.3.042 5
        - m2-bash-completion 2.3 2
        - m2-catgets 1.1 3
        - m2-coreutils 8.25 102
        - m2-dash 0.5.8 2
        - m2-db 5.3.28 3
        - m2-diffutils 3.3 4
        - m2-file 5.25 2
        - m2-filesystem 2016.04 4
        - m2-findutils 4.6.0 2
        - m2-gawk 4.1.3 2
        - m2-gcc-libs 5.3.0 4
        - m2-gdbm 1.11 4
        - m2-gettext 0.19.7 4
        - m2-gmp 6.1.0 3
        - m2-gperf 3.0.4 4
        - m2-grep 2.22 4
        - m2-gzip 1.7 2
        - m2-inetutils 1.9.2 2
        - m2-info 6.0 2
        - m2-less 481 2
        - m2-libasprintf 0.19.7 4
        - m2-libbz2 1.0.6 3
        - m2-libcatgets 1.1 3
        - m2-libcrypt 1.3 2
        - m2-libdb 5.3.28 3
        - m2-libgdbm 1.11 4
        - m2-libgettextpo 0.19.7 4
        - m2-libiconv 1.14 3
        - m2-libintl 0.19.7 4
        - m2-libltdl 2.4.6 3
        - m2-liblzma 5.2.2 2
        - m2-libpcre 8.38 2
        - m2-libreadline 6.3.008 8
        - m2-libtool 2.4.6 3
        - m2-libutil-linux 2.26.2 2
        - m2-libxml2 2.9.2 3
        - m2-m4 1.4.17 5
        - m2-make 4.1 5
        - m2-mintty 1!2.2.3 2
        - m2-mpfr 3.1.4 2
        - m2-msys2-launcher-git 0.3.28.860c495 2
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-ncurses 6.0.20160220 2
        - m2-patch 2.7.5 2
        - m2-perl 5.22.1 2
        - m2-sed 4.2.2 3
        - m2-tar 1.28 4
        - m2-tftp-hpa 5.2 2
        - m2-time 1.7 2
        - m2-ttyrec 1.0.8 2
        - m2-tzcode 2015.e 2
        - m2-unzip 6.0 3
        - m2-util-linux 2.26.2 2
        - m2-which 2.21 3
        - m2-zip 3.0 2
        - m2-zlib 1.2.8 4
        - m2w64-binutils 2.25.1 5
        - m2w64-bzip2 1.0.6 6
        - m2w64-expat 2.1.1 2
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gettext 0.19.7 2
        - m2w64-gmp 6.1.0 2
        - m2w64-libiconv 1.14 6
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-pkg-config 0.29.1 2
        - m2w64-xz 5.2.2 2
        - m2w64-zlib 1.2.8 10
        - make 4.2.1 h301d43c_2004
        - msys2-conda-epoch 20160418 1
        - posix 1.0.0 2
        - vc 14 0
        - vs2015_runtime 14.0.25420 0
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - freetype 2.9.1 h5db478b_1005
        - icu 58.2 vc14_0
        - libiconv 1.15 hfa6e2cd_1004
        - libpng 1.6.35 h7602738_1002
        - libxml2 2.9.8 h9ce36c8_1005
        - vc 14 0
        - vs2015_runtime 14.0.25420 0
        - zlib 1.2.11 h2fa13f4_1004
    run:
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - icu >=58.2,<59.0a0
        - libiconv >=1.15,<1.16.0a0
        - libiconv >=1.15,<1.16.0a0
        - libpng >=1.6.35,<1.7.0a0
        - libpng >=1.6.35,<1.7.0a0
        - libxml2 >=2.9.8,<2.10.0a0
        - libxml2 >=2.9.8,<2.10.0a0
        - vc 14.*
test:
    commands:
        - fc-cache --help
        - fc-cat --help
        - fc-list --help
        - fc-match --help
        - fc-pattern --help
        - fc-query --help
        - fc-scan --help
        - fc-validate --help
        - if not exist %PREFIX%/Library/lib/fontconfig.lib exit /b 1
about:
    description: 'Fontconfig is a library designed to provide system-wide font configuration,

        customization and application access.

        '
    dev_url: https://cgit.freedesktop.org/fontconfig/
    doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
    home: http://www.freedesktop.org/wiki/Software/fontconfig/
    license: MIT
    license_file: COPYING
    summary: A library for configuring and customizing font access
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pkgw
