# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: opencv
    version: 4.0.1
source:
    -   git_rev: 4.0.1
        git_url: https://github.com/opencv/opencv
        patches:
            - 0001-Use-OpenCV_INSTALL_BINARIES_PREFIX-instead-of-hardco.patch
            - 0003-2-pythons-Debug-cmake-dependency-stuff.patch
            - 0004-2-pythons-Debug-all-variables-in-modules-python-CMak.patch
    -   fn: opencv_contrib-4.0.1.tar.gz
        folder: opencv_contrib-4.0.1
        sha256: 0d8acbad4b7074cfaafd906a7419c23629179d5e98894714402090b192ef8237
        url: https://github.com/opencv/opencv_contrib/archive/4.0.1.tar.gz
build:
    number: 0
    run_exports:
        - opencv >=4.0.1,<4.0.2.0a0
    string: py38h2a7c758_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - hdf5 1.10.4 h7ebc959_0
        - icc_rt 2019.0.0 h0cc432a_1
        - openssl 1.1.1d he774522_3
        - py-opencv 4.0.1 py38he44ac1e_0
        - python 3.8.0 hff0d562_2
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - zlib 1.2.11 h62dcd97_3
    run:
        - hdf5 >=1.10.4,<1.10.5.0a0
        - py-opencv 4.0.1 py38he44ac1e_0
        - python >=3.8,<3.9.0a0
test:
    imports:
        - cv2
        - cv2.xfeatures2d
about:
    description: 'OpenCV (Open Source Computer Vision Library) includes several hundreds
        of computer vision algorithms.

        It has a modular structure,which means that the package includes several shared
        or static libraries.

        '
    doc_source_url: https://github.com/opencv/opencv/tree/master/doc
    doc_url: http://docs.opencv.org/
    home: http://opencv.org/
    license: BSD 3-clause
    license_family: BSD
    summary: Computer vision and machine learning software library.
extra:
    copy_test_source_files: true
    final: true
