# This file created by conda-build 3.19.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed Mar 11 18:53:21 2020
# ------------------------------------------------

package:
    name: geos
    version: 3.8.1
source:
    patches:
        - xmltester.cpp.patch
    sha256: 605df3f99056b7bb9c48f20d67e90e539f5a9ca5b2c7896d58ba06e3217dc106
    url: https://github.com/libgeos/libgeos/archive/3.8.1.tar.gz
build:
    number: '0'
    run_exports:
        - geos >=3.8.1,<3.8.2.0a0
    string: he025d50_0
requirements:
    build:
        - cmake 3.16.4 he025d50_0
        - msinttypes r26 2
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
    run:
        - vc >=14.1,<15.0a0
about:
    description: 'GEOS (Geometry Engine - Open Source) is a C++ port of the Java Topology

        Suite (JTS). As such, it aims to contain the complete functionality of

        JTS in C++.

        '
    dev_url: https://github.com/libgeos/libgeos
    doc_url: http://trac.osgeo.org/geos/
    home: http://trac.osgeo.org/geos/
    license: LGPL-2.1
    license_file: COPYING
    summary: Geometry Engine - Open Source
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - msarahan
        - ocefpaf
        - pelson
